apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.51.6
    helm:
      values: |
        server:
          extraArgs:
            - --insecure
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: argocd.example.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: argocd-tls
                hosts:
                  - argocd.example.com
        configs:
          secret:
            argocdServerAdminPassword: "$2a$10$YourHashedPasswordHere"
        dex:
          enabled: false
        notifications:
          enabled: true
        applicationSet:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 