apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-dev

resources:
  - ../../base
  - applications/nginx-ingress.yaml
  - applications/cert-manager.yaml
  - applications/backend-api.yaml

patches:
  - path: patches/argocd-patch.yaml
    target:
      kind: Application
      name: argocd
  - path: patches/app-of-apps-patch.yaml
    target:
      kind: Application
      name: app-of-apps

configMapGenerator:
  - name: argocd-config
    literals:
      - ENVIRONMENT=dev
      - REPO_URL=https://github.com/CLD-3rd/final-team2-manifest.git
      

commonLabels:
  environment: dev
  app.kubernetes.io/environment: dev 