---
# Backend API Deployment (Dev 환경)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-dev
  namespace: backend-dev
  labels:
    app: backend-api
    environment: dev
spec:
  replicas: 1  # Dev 환경: 1개만
  selector:
    matchLabels:
      app: backend-api
      environment: dev
  template:
    metadata:
      labels:
        app: backend-api
        environment: dev
    spec:
      containers:
      - name: backend-api
        # 🐳 Docker Hub 이미지 사용
        image: your-dockerhub-username/backend-api:dev-latest
        imagePullPolicy: Always  # Dev 환경: 항상 최신 이미지
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "debug"  # Dev 환경: 디버그 로그
        - name: DB_HOST_POSTGRESQL
          value: "10.0.20.43"
        - name: DB_HOST_MONGODB
          value: "10.0.30.218"
        resources:
          requests:
            memory: "128Mi"  # Dev 환경: 적은 리소스
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
# Backend API Service (Dev)
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service-dev
  namespace: backend-dev
spec:
  selector:
    app: backend-api
    environment: dev
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
# Backend API Ingress (Dev)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-api-ingress-dev
  namespace: backend-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging  # Dev 환경: Staging 인증서
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://goteego.store"
spec:
  tls:
  - hosts:
    - api-dev.goteego.store  # Dev 환경: 별도 도메인
    secretName: backend-api-dev-tls
  rules:
  - host: api-dev.goteego.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-api-service-dev
            port:
              number: 80
---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: backend-dev 