apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-dev
  namespace: argocd-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.13.3
    helm:
      values: |
        installCRDs: true
        replicaCount: 1  # Dev 환경: 1개만
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m     # Dev 환경: 적은 리소스
            memory: 64Mi
        webhook:
          replicaCount: 1
        cainjector:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Let's Encrypt ClusterIssuer (Staging - Dev 환경용)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@goteego.store
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx 