apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd-prod
spec:
  source:
    helm:
      values: |
        server:
          extraArgs:
            - --insecure
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: argocd.goteego.store
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: argocd-prod-tls
                hosts:
                  - argocd.goteego.store
        # Secret 참조 설정
        secret:
          existingSecret: argocd-prod-secret
        dex:
          enabled: false
        notifications:
          enabled: true
        applicationSet:
          enabled: true
  destination:
    namespace: argocd-prod 