apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-prod

resources:
  - ../../base
  - applications/backend-api.yaml

patches:
  - path: patches/app-of-apps-patch.yaml
    target:
      kind: Application
      name: app-of-apps

commonLabels:
  environment: prod
  app.kubernetes.io/environment: prod 