apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.external_service_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.external_service_name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-target-group-arn: {{ .Values.target_group_arn }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app_label }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
