apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api 
  labels:
    app: backend-api
spec:
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: backend-api
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  selector:
    app: backend-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
