apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CLD-3rd/final-team2-manifest.git
    targetRevision: main # Prod는 main 브랜치를 바라보도록 설정 - 쉽게 말해서 main 브랜치에 어떤 내용이 commit되면 argoCD가 sync할 수 있도록 한다는 의미
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
