apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # 1. 기존 앱과 겹치지 않는 새로운 이름으로 변경
  name: backend-api-refactor-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CLD-3rd/final-team2-manifest.git
    # 2. 가장 중요한 부분: 브랜치 이름을 현재 작업 브랜치로 변경
    targetRevision: refactor/manifest
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    # 3. 기존 dev 환경과 충돌하지 않도록 별도의 테스트 네임스페이스로 변경
    namespace: backend-refactor-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
